ONLYOFFICE/sdkjs

.travis.yml
I added some more test yesterday, so running time
require ~11 minutes on 1-core enviroment.
Seems travis don't like it and failing them.
`travis_wait` may fix the problem
Also extract `docker pull` to separate step, so time to docker pull didn't count in 20-minute timeout.
=> Running test require more than 10 minutes

.travis.yml
Default timeout is 20 minutes, sometime it is not enough.
=> Increase timeout for running doc-builder-testing tests

word/apiBuilder.js
It need for dividing methods on groups.
Default method of dividing is not work because apiBuilder for CDE contains all common methods for all editors
(Default method - is a grouping by filepath)
=> Add tag @typeofeditors ["CDE"]

.travis.yml
For some reason SonarQube download link
is protected with user-password
I found no information about it and support
requiest is quiet, so need to allow failure
until more information.
=> Allow failure for SonarQube Scanner

cell/model/Serialize.js
Open only one SheetView to avoid property conflicts(tabSelected)
=> [se] Fix bug 39511

common/spellcheckapi.js
Check init on checkDictionary. May arrive earlier than initialization
=> [spell] Chech init

word/Editor/Run.js
From now on, we don't add the changes to reviews with changes of the text properties if in fact there have been no changes
=> Fix bug #41833

cell/api.js, cell/utils/utils.js
Use spellcheckState.startCell for detect spellcheck instead of isStart.
Delete unused init in CSpellcheckState
=> [se] Fix bug 46308

word/apiBuilder.js
Adding CSE Methods to Auto Build Jsdoc:
[cell.Api.createradialgradientfill](https://help.onlyoffice.com/products/files/doceditor.aspx?fileid=5004634&doc=SDVGaGVDQmU5OTNVVGw1TmNjVHpNVSs0bmltamdNc3pMWjRvbzhtRU1uST0_IjUwMDQ2MzQi0&action=embedded)
[cell.ApiPresetColor.getclasstype](https://help.onlyoffice.com/products/files/doceditor.aspx?fileid=5004573&doc=cFZUZDVFY2t6OSszd0U3SGpiT01tc2oyY0xxQWgyaXNJUXR0a0xsYWtiRT0_IjUwMDQ1NzMi0&action=embedded)
[cell.ApiRun.getclasstype](https://help.onlyoffice.com/products/files/doceditor.aspx?fileid=5006292&doc=SEF3VDUrYUdOWkJURlZLZ3p1NTFWVHBDajdRZStQWUZpVXZVamYwNkdJdz0_IjUwMDYyOTIi0&action=embedded)
=> Add the type of editors "CSE" for metods

word/Editor/ParagraphContentBase.js
From now we do not replace all runs in the form with the new empty single run, we combine it in the one single run
=> Fix bug #48394

word/api.js
Now function GetTextFormAutoWidth returns twips instead of mm
=> For bug #49727

cell/apiBuilder.js, slide/apiBuilder.js, word/apiBuilder.js
Added return values to ApiTextPr methods.
Added methods for Get Width/Height of presentation
Added parent checkin to ApiTextPr.prototype.private_OnChange method
=> [apibuilder] Added methods for creating and adding word arts.

.github/workflows/check.yml
It was changes almost a year ago in:
https://github.com/ONLYOFFICE/doc-builder-testing/pull/541
But seems I forgot to change it here (
Also no point in using `develop` version, since the stable version, well... it's stable?
=> Fix incorrect docker image name used in unit-tests

common/plugins/connector/connector.js
updated descriptions for connector
=> Descriptions for connector

cell/apiBuilder.js, slide/apiBuilder.js, word/apiBuilder.js
=> Api documentation

common/plugins/plugin_base_api.js
added description for the InpurHelper class
=> Input helper description

cell/api.js, cell/model/PivotTables.js, cell/model/Workbook.js, tests/cell/spreadsheet-calculation/PivotTests.js
Added asc_getShowDetailsSheetName method.
Refactoring show-details.
=> [pivot] New sheet names for show-details.

common/apiCommon.js
It's necessary, because we have problem with some plugins in viewer and also we lose field "descriptionLocale".
=> [plugins] Add two missed fields from plugin`s config to serrialize/deserialize functions.

common/macros.js
Disable "function.constructor" and "new Function" for macros.
=> Fix bug #48195.

word/Editor/Document.js
Separate the canCopy and canCut checks in filling form mode
=> Fix bug #65744

word/apiBuilder.js
Stop preventing duplicating anchored images when copying a paragraph using builder script
=> Fix bug #66963

word/Editor/Serialize2.js
Keep doNotExpandShiftReturn option when saving to docx
=> Fix bug #67226

word/Math/LaTeXParser.js, word/Math/matrix.js, word/Math/operators.js
- Fix get linear math for LaTeX matrix with "\begin{}\end{}" constructions
=> Fix bug #61007

common/Charts/ChartsDrawer.js, common/Drawings/Format/ChartSpace.js
Forward/backward attributes for trendlines are now displayed correctly 
labels are also fixed for the cases when forward/backward attributes are set
=> [all] Trendlines forward/backward fixes
