ONLYOFFICE/sdkjs

cell/view/WorksheetView.js

symbol '.' in find-replace string value

fix bug 32795

---

cell/view/CellEditorView.js
cell/view/StringRender.js

replace \n -> empty in the cell without wrap

fix bug 17590

---

common/Private/license.js
common/apiCommon.js

add method asc_getBuildVersion
fix bug 33186

add read build version from server

---

common/editorscommon.js
slide/Local/api.js

async load desktop scripts support

presentation with password

---

cell/view/CellEditorView.js
cell/view/EventsController.js

fix bug 33908

---

cell/api.js
slide/api.js
word/api.js

sequence:
- load document
- load sdk before load fonts and crash on an attempt to send styles event

fix open error

---

.travis.yml

This achieved by using travis build stages

Stop travis build if any line ended with failure

---

cell/view/WorksheetView.js

fix bug with print or save as pdf in builder big files

set min limit of sector size

---

cell/view/WorksheetView.js

Revert "set min limit of sector size"

---

common/Drawings/Format/Format.js

fix Bug 35307

---

slide/Editor/Format/Comments.js

fix bug 35408

---

common/Drawings/States.js

fix Bug 35451

---

.travis.yml

Need to fix test run on travis ci

Use develop version of doc-builder-testing

---

.travis.yml

Forgot use tag `develop-latest` in docker run,
so it run `latest` tag instead.
Also - split line for better readablity

Fix incorrect travis

---

slide/api.js
word/api.js

IE reporter bug & new method for plugins

---

.codeclimate.yml

add ratings to codeclimate

---

common/Private/license.js
common/apiCommon.js

in server trial -> mode
add Asc.c_oLicenseMode enum

asc_getTrial -> asc_getLicenseMode

---

cell/model/ConditionalFormatting.js
cell/model/FormulaObjects/parserFormula.js
cell/model/Workbook.js

support percentile in conditional formatting

fix bug 36099

---

cell/model/PivotTables.js
cell/model/Workbook.js

all fields can check compact property and pivot table can check compactData property for filter on all rows

fix bug 36482

---

cell/apiBuilder.js

[new function] Add new function SetRowHeight

---

cell/model/Workbook.js

reproduced on this sequence [1, blank, 2, 3]
for bug #36807

[se][bug] Fix js error with autofill

---

CHANGELOG.md
cell/apiBuilder.js

Add new functions and property

Feature/get hidden, set hidden, hidden

---

CHANGELOG.md
cell/apiBuilder.js

Functions: GetColumnWidth, SetColumnWidth
Properties: ColumnWidth, Width

Add new functions and properties in ApiRange

---

word/api.js

Fix crash on pdf reconnect or check idle

[de] Fix crash

---

cell/model/PivotTables.js
cell/model/Workbook.js

Fix open pivot tables with VALUES

[se] Fix pivot

---

common/apiBase.js

Revert "[de][se][pe] Change error message on restore connection in case of fi…"

---

cell/model/Workbook.js

One of scenarios:
-new spreadsheet
-set value: A1:1, B1:=A1
-insert B col
-set value: A1:2
-value in B2 still - 1

[se] Fix formula dependency and file assemble after add col/row

---

cell/view/WorkbookView.js

[se][mobile] Fix crash

---

slide/apiBuilder.js
word/apiBuilder.js

There are some common methods in add editors. It is placed in word/apiBuilder.js. They were  commented too

Add comments for all methods for builder, CPE

---

cell/view/StringRender.js

Fix hyphenation for some east asian symbols

[se] Fix hyphenation

---

cell/view/EventsController.js

Delete change cursor on canvas

[se] Fix bug 38401

---

cell/api.js

Update all sheets lock on update workbook lock

[se] Fix bug 38882

---

cell/view/WorksheetView.js

[se] Fix bug 38754

---

cell/model/Workbook.js

Adjust nRowsCount/nColsCount by non-empty cells

[se] For bug 38754

---

common/editorscommon.js
word/Editor/GraphicObjects/Format/ShapePrototype.js

Fix drawing recalculate bug;

---

cell/view/WorksheetView.js

Fix calculate vertical position for center align and top align

[se] Fix bug 39023

---

slide/Drawing/Transitions.js
slide/api.js

Use DemonstrationManager.Mode to check transition slides instead of canSave

[pe] Fix bug 37896

---

cell/view/WorksheetView.js

For hyperlink: first set the value, then set hyperlink

[se] Fix bug 39060

---

word/Editor/Run.js

Fix the problem of replacing text inside a math equation

Fix bug #39077

---

cell/apiBuilder.js
cell/model/Workbook.js

setLocale and getLocale in apiBuilder and change setValue and setName

[new functions] Add new functions 

---

cell/view/WorksheetView.js

Draw after insert function in autocompleate

[se] Fix bug 39222

---

cell/view/WorksheetView.js

Fix draw active cell in selection with freeze pane

[se] Fix bug 39395

---

cell/model/Workbook.js
cell/model/WorkbookElems.js

Use A1 mode for copy sparklines

[se] Fix bug 39906

---

cell/view/WorksheetView.js

[se] Fix bug 39716

---

cell/model/Workbook.js

Check zero column width (means hidden)

[se] Fix bug 40352

---

cell/view/WorksheetView.js

Fix scroll to cell with frozen pane

[se] Fix bug 40294

---

CHANGELOG.md
cell/apiBuilder.js

GetSelection, AddDefName, GetDefName, property: Selection and remove function Add in ApiName.

Add new fuctions: 

---

CHANGELOG.md
cell/apiBuilder.js

Add function GetComments and property Comments in ApiWorksheet. Add function GetComment and property Comment in ApiRange. Add function GetText and property Text in ApiComment.

Add new class ApiComment in apiBuilder.

---

cell/view/WorkbookView.js
cell/view/WorksheetView.js

Disable change row height and column width in cell edit mode. Change cursor type in cell edit mode

[se] Fix bugs 16522, 36458

---

cell/view/CellEditorView.js

Style changes are disabled in formula editing mode

[se] Fix bug 40637

---

cell/view/WorkbookView.js

Tooltip is disabled in edit mode

[se] Fix bug 36458

---

cell/utils/utils.js
cell/view/EventsController.js
cell/view/WorkbookView.js
cell/view/WorksheetView.js

Click on the hyperlink via MouseUp. Follow the link in the first second after MouseDown.

[se] Fix bug 37930

---

cell/view/WorkbookView.js

[se] Fix bug 41075

---

cell/view/EventsController.js

Changed combination to select columns on MAC (“Opt + Spacebar")

[se] Fix bug 40902

---

cell/model/Workbook.js
cell/view/WorksheetView.js

[se] Fix bug 39039

---

cell/view/WorksheetView.js

[se] Fix bug 41516

---

.travis.yml

Before task just failed without any info

Output problematic files in travis check

---

common/NumFormat.js

Fix day of week in 1904 date mode

[se] Fix bug 41713

---

word/Editor/Serialize2.js

[de] Add Gutter to Editor.bin

---

cell/view/WorksheetView.js

[se] Fix bug 41787

---

word/Editor/DocumentChanges.js
word/Editor/DocumentContentChanges.js

Fix the problem with updating indexes on undo/redo

Fix bug #41846

---

word/Editor/ParagraphContentBase.js

Fix the problem with updating positions in the inner classes within a paragraph

Fix bug #41848

---

word/Editor/Serialize2.js

Replace ReplacePlaceHolderWithContent with RemoveFromContent

[de] Fix bug 42536.

---

cell/view/WorksheetView.js

Fix draw cells with overlap text and background color

[se] Fix bug

---

cell/view/WorksheetView.js

Fix calculate height with wrap

[se] Fix bug 42471

---

word/Private/TrackRevisions.js

Fixed the problem with accepting / rejecting selected content when moved text gets into selection

Fix bug #42117

---

word/Editor/Spelling.js

Fix the problem with spelling check for Korean symbols

Fix bug #42538

---

common/commonDefines.js

[se] Fix bug 42627

---

word/Editor/StructuredDocumentTags/SdtPrChanges.js

Fix the problem with drawing a track around a content control

Fix bug #42657

---

word/Editor/Document.js
word/Editor/Paragraph.js
word/Editor/Paragraph/ParaRevisionMove.js
word/Editor/Run.js
word/Private/TrackRevisions.js

Fix the problem with accept/reject in case when moved text gets into selection

Fix bug #42665

---

word/Editor/Run.js

Fix the problem with deleting text that was previously added by the same user

Fix bug #41242

---

cell/model/PivotTables.js

Create pivot style on constructor. May be absent in some files

[se] Pivot

---

.travis.yml

Actualize sonar-scanner-cli tool

---

word/api.js

Add plugin methods to move the cursor to the start/end of the document

Fix bug #41521

---

.travis.yml

Since:
https://github.com/ONLYOFFICE/sdkjs/commit/c9d53626cfff6ee378900c212f5aa6a573a58ecc

Fix travis test after changing destonation dir

---

word/Editor/Paragraph.js

Fix the problem with setting the direct properties of a paragraph

Fix bug #44035

---

word/Editor/Table.js

Fixes for some critical and memory leaks

Bugs fixes

---

cell/view/WorksheetView.js

Send error on change pivot table value on find-replace

[se] Fix bug 43988

---

cell/view/WorksheetView.js

[se] Fix bug 43920

---

cell/model/CellComment.js
cell/model/Serialize.js

For comments without dimensions

[x2t] Fix bug 38945

---

cell/view/WorksheetView.js

[se] Fix bug 43957

---

word/Editor/Paragraph/ParaDrawing.js

Prevent changing  image wrapping style

For bug #44173

---

common/commonDefines.js
word/api.js

[de] For bug 44161

---

word/api_plugins.js

updating some comments for plugin methods because documentation in api.onlyoffice.com and in code must be same
Adding examples for methods.

Update comments for plugins

---

cell/view/WorksheetView.js

Continue calculate after find merge cell

[se] Fix bug 43806

---

word/Editor/Document.js
word/Editor/DocumentContent.js
word/api.js

Fix the problem with calculating the bottom limit of recalculation for frames

Fix bug #44213

---

word/Editor/Document.js
word/Editor/History.js

Add the ability to specify the state of the document selection when adding a new point to the history

Fix bug #44257

---

common/Drawings/Format/Format.js
common/Drawings/Metafile.js
word/api.js

1) Fix bug 43741

---

cell/model/History.js

Set selection after draw on undo/redo end

[se] Fix bug 43966

---

cell/model/CellComment.js

[se] Fix bug 43020

---

common/GlobalLoaders.js
common/editorscommon.js
word/Drawing/DrawingDocument.js
word/Drawing/buttons.js

Add retry for image requests and loadScript

[all] Fix bug 44157

---

word/Editor/Numbering/NumberingLvl.js

Fix the problem with font selection for numbering characters

Fix bug #44011

---

common/Drawings/Format/Shape.js
word/Editor/Comments.js
word/Math/mathContent.js

Fix the problem with CheckRunContent function

Fix bug #44476

---

cell/utils/utils.js

Fix calculate px to pt and pt to px for retina

[se] Fix bug 42900

---

common/apiBase.js
word/api.js

Move LoadFontsFromServer to base. Rename LoadFontsFromServer -> asc_loadFontsFromServer

[all] Move

---

common/editorscommon.js

loadScriptBackoff -> loadScriptWithBackoff

[all] For bug 44522

---

word/Editor/Field.js

Fix the problem with highlighting simple fields in header/footer

Fix bug #44600

---

cell/view/WorksheetView.js

Check merged on rows for empty cell with format

[se] Fix bug 44638

---

common/apiCommon.js
common/wordcopypaste.js
word/Editor/Comments.js
word/Editor/Serialize2.js
word/api.js

Fix DurableId. Numbers greater than 0x7FFFFFFE cause MS Office errors(ST_LongHexNumber by spec)

[de] Fix bug 44689

---

cell/model/WorkbookElems.js

Support flag auto for fgColor for solid fill

[se] For bug 44748

---

word/apiBuilder.js

Added the Push() function for the document and paragraph
Added the Last() function for the document and paragraph
Added the Delete() function for paragraph and run
Added ability to apply text settings directly to a run or paragraph

Added new functions for working with ApiBuilder 

---

cell/model/DataValidation.js

Validate values without format

[se] For bug 44879

---

cell/view/WorksheetView.js

Convert values for data validation to string

[se] Fix bug 44950

---

cell/model/DataValidation.js

Check Whole numbers for data validation. Check not number for data validation.

[se] Fix bug 44928

---

word/Editor/DocumentContent.js
word/Editor/GraphicObjects/GraphicObjects.js
word/Editor/Paragraph.js

Fix the problem with positioning of a frame in the header, also fix the problem with calculating wrapping bounds of such frames

Fix bug #44975 #45040

---

word/Editor/DocumentContent.js
word/Editor/GraphicObjects/GraphicObjects.js
word/Editor/Paragraph.js

Revert "Fix bug #44975 #45040"

---

word/Editor/Document.js
word/Editor/DocumentContent.js
word/Editor/DocumentContentElementBase.js
word/Editor/DocumentControllerBase.js
word/Editor/DrawingsController.js
word/Editor/Footnotes.js
word/Editor/GraphicObjects/GraphicObjects.js
word/Editor/HeaderFooter.js
word/Editor/HeaderFooterController.js
word/Editor/LogicDocumentController.js
word/Editor/Paragraph/ParaDrawing.js
word/Editor/StructuredDocumentTags/BlockLevel.js
word/Editor/Table.js
word/api.js

Implement adding several count of table rows/columns

Fix bug #20179

---

word/apiBuilder.js

New ApiTable methods

---

cell/apiBuilder.js
word/apiBuilder.js

Methods for mail merge for apiBuilder.
Methods for extracting mail merge data from Spreadsheets.

apiMailMerge

---

cell/view/WorksheetView.js

Fix draw merge cell with color

[se] Fix bug 45922

---

word/Editor/Paragraph.js
word/Editor/Styles.js

Implement merging frame properties from a style

Fix bug #45730

---

word/Editor/Endnotes.js

Fix the problem with numbering in endnotes

Fix bug #37901

---

word/Editor/Paragraph.js

Implement saving numbering values when copy/paste to text

Fix bug #22928

---

common/intervalTree.js

[license] Fix

---

cell/model/DataValidation.js

Use getSelection() instead of selectionRange

[se] Fix bug 45973

---

common/Drawings/CommonController.js

some shape types were treated as connectors what broke files after saving

[drawings] Fix problem with broken files:

---

word/Editor/Document.js

Fix the problem with drawing frames and floating tables on the page with several sections

Fix bug #46001

---

cell/graphics/pdfprinter.js

Add return to printer setLineDash

[se] Fix bug 46005

---

word/Editor/Run.js

Fix "smart quotes" for different languages

Fix bugs #45591 #45790 #33710

---

word/Editor/Numbering/Num.js
word/Editor/Paragraph.js
word/Editor/ParagraphContent.js
word/Editor/Run.js
word/api.js

Implement subscript/superscript text properties for the end of paragraph mark and for numbering symbol

Fix bug #11135

---

common/apiBase.js

[all] Fix bug 41649

---

cell/view/CellEditorView.js

Check max cell size on composite input

[se] Fix bug 39867

---

cell/api.js
cell/apiBuilder.js
cell/model/CellComment.js
cell/model/Workbook.js
cell/model/autofilters.js
cell/model/clipboard.js
cell/native/native.js
cell/view/WorkbookView.js
cell/view/WorksheetView.js
common/Charts/DrawingObjects.js

Revert "[se] Fix select"

---

word/Editor/Paragraph.js
word/Editor/Table.js

Fix the problem with sending locks

Fix bug #46078

---

cell/view/CellEditorView.js

[se] Fix bug 27006

---

word/Editor/StructuredDocumentTags/InlineLevel.js

Fix the problem with selection when changing content controls placeholder text

Fix bug #46108

---

word/Editor/StructuredDocumentTags/InlineLevel.js

Fix the problem with deleting content controls

Fix bug #46121

---

cell/model/DataValidation.js

Add check "none" type in data validation

[se] Fix bug 45200

---

cell/view/EventsController.js

[se] Fix bug 46153

---

word/Editor/Table.js

Fix the problem with calculating table width when changing table columns widths

Fix bug #46167

---

cell/view/WorksheetView.js

Disable some cursors on edit cell and select dialog

[se] Fix bug 46211

---

cell/api.js

Use setSelection for spellChecker

[se] Fix bug 43551

---

cell/model/Workbook.js
cell/view/WorksheetView.js

Get xfs return compiled (with tables or CF) or original xfs

[se] Fix bug 46191

---

cell/api.js

Fix create bookmark to error range. All links in A1-mode

[se] Fix bug 46264

---

cell/view/CellEditorView.js

Use string of selectionDirection. Replace after updating closure-compiler to version

[se] Fix bug 43569

---

word/Math/base.js

Fix the problem with applying text properties to equation

Fix bug #46335

---

word/Editor/Document.js
word/Editor/GraphicObjects/DrawingStates.js
word/Editor/Paragraph/ParaDrawing.js

Now we do not allow to copy/add/move shapes inside the footnote/endnote

Fix bug #46347

---

cell/api.js
cell/model/History.js
cell/model/Workbook.js
cell/utils/utils.js
cell/view/WorkbookView.js
cell/view/WorksheetView.js

New changeSheetViewSettings. Add update after change.

[se] Fix bug 27060

---

cell/.unit-tests/PivotTests.js

[se] Delete

---

cell/api.js
common/apiBase.js
slide/api.js
word/api.js

Delete duplicate asc_setRestriction

[all] Delete

---

cell/api.js

Always send styles in edit mode. Don't check restrictions.

[se] Fix 46674

---

cell/view/WorksheetView.js

Delete set selection in history point from _autoFitColumnWidth.

[se] Fix bug 46639

---

word/Editor/DocumentContent.js

Fix the problem with drawing content controls track in the header

Fix bug #46668

---

cell/view/WorkbookView.js
cell/view/WorksheetView.js

Lock add, edit and delete defNames without restrictions or view mode

[se] For bug 46703

---

cell/model/Serialize.js
cell/model/Workbook.js
common/SerializeCommonWordExcel.js
common/Shapes/Serialize.js
common/Shapes/SerializeWriter.js
slide/Editor/Format/Comments.js
slide/Editor/Format/Presentation.js
word/Editor/Document.js
word/Editor/Serialize2.js

Add reading/writing of customProperties

[all] For bug 46739

---

cell/model/DrawingObjects/DrawingDocument.js
cell/native/DrawingDocument.js
common/Charts/DrawingArea.js
common/Drawings/CommonController.js
common/Native/Wrappers/DrawingDocument.js
common/editorscommon.js
slide/Drawing/DrawingDocument.js
slide/Drawing/HtmlPage.js
slide/Native/Wrappers/DrawingDocument.js
word/Drawing/DrawingDocument.js
word/Drawing/HtmlPage.js
word/Editor/Paragraph.js
word/Editor/StructuredDocumentTags/InlineLevel.js

Move formulas tracks to separate class;
implement formula selection in cells and presentations

[math-select] Formulas selection:

---

word/Editor/Sections.js

If CountBy is not specified in the line numbering, we assume that line numbering is not specified at all

Fix bug #46875

---

cell/apiBuilder.js
word/apiBuilder.js

Added GetClassType() methods

---

word/Editor/Paragraph.js

Fix the problem with auto distance for line numbers

Fix bug #47012

---

word/Editor/Document.js

Implement the function of getting sections by selection

For bug #47254

---

cell/Local/api.js

(cherry picked from commit bbfa7b723cdb77f7a7ccaeddbbda79939c9cd4a8)

Fix bug 47229 (#1343)

---

word/Editor/Document.js
word/Editor/DocumentContent.js
word/Editor/DocumentContentElementBase.js
word/Editor/DocumentControllerBase.js
word/Editor/DrawingsController.js
word/Editor/Endnotes.js
word/Editor/HeaderFooter.js
word/Editor/HeaderFooterController.js
word/Editor/LogicDocumentController.js
word/Editor/Paragraph.js
word/Editor/StructuredDocumentTags/BlockLevel.js
word/Editor/Table.js
word/Editor/Table/TableCell.js

Improve performance of moving cursor up/down

Fix bug #47299

---

word/Editor/DocumentContentBase.js
word/Editor/Table/TableRecalculate.js

Fix the problem with calculating endnotes in the table

Fix bug #47448

---

common/editorscommon.js
common/plugins.js

(cherry picked from commit b94b159cd6e19ad7212554823fed7d7f4a1ac54f)

Fix bug 46869

---

word/Editor/Document.js
word/Editor/Endnotes.js
word/Editor/Sections.js
word/apiDefines.js

Export constants for position of footnotes/endnotes

For bug #47445

---

word/Editor/Endnotes.js
word/Editor/Paragraph.js

Fixed problem with defining cursor update inside endnote

Fix bug #47505

---

word/Editor/ParagraphContent.js
word/Editor/Paragraph_Recalculate.js

Fix problem with calculating of the endnote number in some cases

Fix bug #47554

---

word/Editor/Paragraph.js
word/Editor/Run.js

Fix the problem with text properties around endnote reference

Fix bug #47602

---

word/Editor/Document.js
word/Editor/Sections.js
word/api.js

Add function for receiving the count of sections in the document

For bug #47607

---

word/Editor/ParagraphContent.js

Fix the problem with copying footnote/endnote ref outside the note

Fix bug #47608

---

word/Editor/Document.js

Prevent adding footnote/endnote references inside an equation

Fix bug #47628

---

word/Editor/Paragraph.js
word/Editor/Sections.js

Fix the problem with saving/loading start parameter for line numbers

Fix bug #47627

---

word/Editor/DocumentContent.js
word/Editor/Endnotes.js
word/Editor/Footnotes.js

Fix the problem with converting endnotes to footnotes and vice versa

Fix bug #47623

---

word/apiBuilder.js

Fix the problem with inserting inline-level content controls via builder

Fix bug #47423

---

cell/native/native.js

Closure this to t, for jscore ios

[ios] fix chart editor

---

word/Editor/StructuredDocumentTags/BlockLevel.js
word/Editor/StructuredDocumentTags/InlineLevel.js
word/Editor/StructuredDocumentTags/SdtBase.js

Fix the problem with coping of the custom placeholder for content controls

Fix bug #48117

---

word/Editor/ParagraphContentBase.js

Fix issue with backspace/delete buttons for ComboBox form

Fix bug #48130

---

word/Editor/StructuredDocumentTags/SdtPr.js

For bug #48107

---

word/Editor/Paragraph/ParaDrawing.js

Fix the problem with moving shapes inside forms

Fix bug #48174

---

word/apiCommon.js

Change the default settings for TOC

Fix bug #48331

---

word/Editor/ParagraphContent.js
word/Editor/Run.js
word/Editor/StructuredDocumentTags/SdtPr.js

Comb text form with maxCharacter value of more that 1000 is no longer consider as a comb text form

Fix bugs #48399 #48403

---

word/api.js

Add possibility to paste in the filling form mode

Fix bug #48436

---

word/Editor/Paragraph/ComplexField.js
word/Editor/Paragraph/ComplexFieldInstruction.js

Fix the problem with updating complex field instruction

Fix bug #48446

---

word/Editor/Document.js

Allow to clear all forms in filling forms mode

Fix bug #48441

---

word/Editor/Math.js

Fix the problem with calculating equations divided into several pages and wrapped around images

Fix bug #48529

---

word/Editor/Table/TableRecalculate.js

Fix the problem with calculating preferred widths for table columns

Fix bug #48725

---

word/Editor/Run.js
word/Editor/Table/TableCell.js

Also fix the problem with calculating of the min/max content width of the text that contains hyphens

Fix bug #48864

---

slide/api.js
word/api.js

Clear history when adding a signature to document/presentation

For bug #48835

---

common/Native/native_graphics.js

removed access to properties whose names were collapsed

fix put_BrushGradient

---

common/Drawings/Format/ChartFormat.js

revert asc_getYValuesArr function
rename checR1C1ModeForExternal -> checkR1C1ModeForExternal

[bug] Fix previous commit:

---

common/apiBase_plugins.js
word/apiBuilder.js

Added method for common plugins API.

---

word/Editor/StructuredDocumentTags/BlockLevel.js

Fix the problem with removing temporary content control wrapper

Fix bug #49090

---

word/Editor/Run.js

From now the height of comb form will not depend on the content

Fix bug #49129

---

word/apiBuilder.js

Fixed method.

---

word/Editor/Document.js
word/Editor/DocumentContentBase.js
word/Editor/Table.js

Improve deleting of a table row when track changes is on

Fix bug #49270

---

word/api.js

Added missing export function "SetDrawImagePreviewBulletChangeListLevel"

Added missing export

---

word/Editor/ParagraphContentBase.js

Fix the problem with setting parent class for run

Fix bug #49451

---

word/Editor/Table.js
word/Editor/Table/TableRow.js

Fix the problem with compiling table cell properties

Fix bug #49443

---

cell/apiBuilder.js

some changes for the property descriptions

Builder descriptions

---

word/apiBuilder.js

Fix bug #49247

---

word/Editor/Document.js

Fix bug #50876

---

word/Editor/Paragraph/ComplexFieldInstruction.js
word/Editor/Run.js

Fix the problem with TOC field, when "o" and "t" switches are not specified. Also fix collecting of a complex field and it's instruction for reviewed parts of text

Fix bug #50596

---

word/Editor/Run.js

Fix calculation of the position of anchored drawings that are located in front/behind the text

Fix bug #50253

---

common/HistoryCommon.js
word/Editor/Document.js
word/Editor/Run.js
word/Editor/StructuredDocumentTags/InlineLevel.js
word/Editor/StructuredDocumentTags/SdtBase.js
word/api.js

Don't use the "position" property for text within a fixed form

Fix bug #51068

---

common/SerializeCommonWordExcel.js

Fix writing shade color from theme

Fix bug #50943

---

word/Editor/Document.js
word/Editor/Run.js

Fix the problem with adding a hyperlink in the review mode, in case when displayed text didn't change.
Also correct the position of the cursor after removing text in the review mode

Fix bug #48162

---

slide/Editor/Format/Comments.js
word/Editor/Comments.js
word/Editor/Field.js
word/Editor/Math.js
word/Editor/Paragraph.js
word/Editor/Paragraph/ParaDrawing.js
word/Editor/ParagraphContentBase.js
word/Editor/Run.js
word/Editor/StructuredDocumentTags/InlineLevel.js
word/Math/base.js
word/Math/mathContent.js

Fix the problem with calculating the position and the page number of drawing objects when we simply moving doccontent instead of full recalculation

Fix bug #51175

---

word/api.js

Fix the problem with minimization

Fix bug #51226

---

word/Editor/Document.js

Fix the problem with calculating header/footer after calculating the number of document pages in native editors

Fix bug #50640

---

word/apiBuilder.js

Changed method of creating "oShd.Fill" field

Fix bug #51582

---

common/CollaborativeEditingBase.js

Fix the problem with marking classes as non recalculated after loading changes

Fix bug #51599

---

word/Editor/Document.js
word/apiCommon.js

Method to creating function have been changed and parameters have been renamed.

Fixed problem with unit tests.

---

common/commonDefines.js
word/apiDefines.js

move c_oAscDisplayModeInReview from word to common

[se] Fix bug 51986

---

cell/model/Serialize.js

add check on read data validation

[se] By bug 51959

---

cell/apiBuilder.js

added new api descriptions for cell methods

Api descriptions

---

word/Editor/Table/TableRecalculate.js

Handle simple situation with table wrapping around flow objects

Fix bug #51079

---

word/Editor/Common.js

Fix the problem with counting rows in window for converting text to table

Fix bug #52145

---

word/Editor/Document.js
word/Editor/DocumentContentBase.js

Fix the problem with converting text to table inside autoshapes

Fix bug #52149

---

common/wordcopypaste.js

Clear the content of all cells before paste

Fix bug #52196

---

word/Editor/Paragraph.js

Fix bug #52239

---

word/Editor/Document.js

Added application of framepr to CTable and CBlockLevelSdt in process of converting table to text

Fix bug #52603

---

common/Native/native.js

(cherry picked from commit 018d67de5daabbfa1629205f2b38170d352ebc42)

Fix bug 52684

---

word/Editor/GraphicObjects/WrapManager.js

prevent crash on requesting wrapping intervals before page was recalculated

[bug] Fix bug 52734:

---

word/Editor/Table/TableRecalculate.js

Fix bug #52774

---

word/Editor/Document.js

Fix bug #53618

---

cell/model/WorkbookProtection.js

[se] For protection history

---

common/wordcopypaste.js

Support tag, title, content lock

[se] By bug 53905

---

common/Drawings/Format/Shape.js
word/Editor/DocumentContent.js
word/Editor/Paragraph.js
word/Editor/Paragraph_Recalculate.js
word/Editor/StructuredDocumentTags/InlineLevel.js

From now we can't change the vertical adjustment of the text inside forms.
For single-line forms adjust text to center and for multi-lined forms to the top with an offset

For bug #53266

---

common/Drawings/Format/Shape.js
word/Editor/Paragraph_Recalculate.js

Remove drawing selection of a fixed forms in the filling form mode. Also fix several problems with special padding for fixed forms in case of picture form and checkboxes

Fix bug #54308

---

word/Editor/Document.js
word/Editor/DocumentContent.js
word/Editor/DrawingsController.js

Fix the problem with filling picture form via copying

Fix bug #54306

---

common/HistoryCommon.js
word/Editor/Paragraph/ParaTextPr.js
word/Editor/Paragraph/ParaTextPrChanges.js
word/Editor/Run.js
word/Editor/RunChanges.js

Fix the problem with specifying font of run in case when theme fonts uses in that run

Fix bug #52678

---

word/Drawing/buttons.js

Fix bug 54296

---

word/Editor/Document.js
word/Editor/DocumentContent.js
word/Editor/DrawingsController.js
word/Editor/Paragraph.js

Fix the problem with adding comments to pictures

Fix bug #54826

---

cell/api.js

There is nothing to print because the table is empty

[se] By bug 55218

---

word/Editor/Document.js

Fix the problem with calculating page count stage

Fix bug #55458

---

word/Editor/Table/TableCell.js
word/Editor/Table/TableRecalculate.js

Fix the problem with text position calculation for rotated table cells

Fix bug #54200

---

cell/apiBuilder.js
slide/apiBuilder.js
word/apiBuilder.js

updated api descriptions for new methods

New api descriptions

---

word/apiBuilder.js

small updates for api descriptions

Api descriptions for word methods

---

word/apiBuilder.js

small fixed for api descriptions

Fixes for api descriptions

---

cell/apiBuilder.js
slide/apiBuilder.js
word/apiBuilder.js

last api description updates for 7.1

Api description updates for 7.1

---

common/Drawings/Format/Data.js
common/Shapes/SerializeWriter.js

* Use ShapeStyle instead of StyleData in PrSet
* Fix writing of non graphic smartArt properties (may cause corruption of files with animated smartArts)

[bug] for bug 57070:

---

common/Charts/DrawingObjects.js
common/Drawings/Format/Data.js
common/Drawings/Format/GraphicObjectBase.js
common/Drawings/Format/GroupShape.js
common/Drawings/Format/Shape.js
common/Drawings/TrackObjects/ResizeTracks.js
word/Editor/GraphicObjects/Format/GroupPrototype.js

check text position in grouped smartart

For bug "grouped smart art"

---

cell/model/History.js
common/apiBase.js
word/Editor/History.js
word/Editor/Paragraph/ParaDrawing.js

Fix the problem with registering some classes in build for native builder

Fix bug #48473

---

word/Editor/Document.js

Fix the problem with calculating the document without recursion

Fix bug #57236

---

cell/api.js

Update cell info after set localization

[se] By bug 56175

---

.github/workflows/check.yml

They do not work without newest build of DocumentBuilder standalone

Fix failing tests

---

common/Native/Wrappers/api.js

Replaced override method calls with parent methods. Is this correct? What were they used for?

Fix bug #58458

---

cell/apiBuilder.js
slide/apiBuilder.js
word/apiBuilder.js

Api documentation updates

---

cell/apiBuilder.js
common/apiBase_plugins.js
slide/apiBuilder.js
word/apiBuilder.js
word/api_plugins.js

Api docs fixes

---

common/apiBase.js

(cherry picked from commit ef6e3a8c260e48e16ee97892ac6f90eb51129abf)

Fix bug 59414

---

word/Editor/Paragraph.js
word/Editor/Paragraph_Recalculate.js

Fix the problem with compiling text properties of paragraph numbering

Fix bug #59324

---

common/libfont/map.js

(cherry picked from commit 5a54cb15418ac7da6625eb5c54d71414456cc017)

Change selection font for base math font

---

common/commonDefines.js
common/wordcopypaste.js

Send error event ID.CanNotPasteImage

[se] By bug 52224:

---

word/Editor/Paragraph.js

Fix the problem with calculating style of paragraph numbering

Fix bug #59904

---

word/Editor/Paragraph.js

Fix comment highlight rendering

Fix bug #59640

---

cell/apiBuilder.js
cell/view/CellEditorView.js

Also make some changes in "CellEditor" methods.

[se] Add new classes in api builder "ApiCharacters" and "ApiFont".

---

word/Editor/Math.js
word/Math/LaTeXParser.js
word/Math/NamesOfLiterals.js
word/Math/UnicodeParser.js
word/Math/mathContent.js

Fix bug 59871
Fix bug 60082
Fix bug 60143
Fux bug 60142

[de] Fix bug 60219

---

cell/api_plugins.js
common/apiBase_plugins.js
slide/api_plugins.js

updated the plugin descriptions for 7.3

Plugin api descriptions

---

cell/apiBuilder.js
word/apiBuilder.js

updated api descriptions for 7.3

Api descriptions 7.3

---

cell/apiBuilder.js
common/apiBase_plugins.js
common/plugins/plugin_base_api.js
slide/apiBuilder.js
word/apiBuilder.js
word/api_plugins.js

small fixes for api descriptions 7.3

Api descriptions fixes

---

word/Editor/Paragraph.js
word/Editor/Search/DocumentSearch.js

Send search result as three separated strings before match/found match/after match

For bug #60109

---

word/Editor/Document.js
word/Editor/Paragraph.js
word/Editor/Run.js
word/Editor/Table.js
word/Editor/Table/TableCell.js
word/Editor/Table/TableRow.js

Fix the problem with compiling styles and updating fields on document load

Fix bug #61223

---

word/Math/LaTeXParser.js
word/Math/NamesOfLiterals.js

+ fix LaTeX \below and \above tokens processing in degree and index blocks

Fix bug #61342

---

common/Drawings/CommonController.js

[bug] fix bug 61597:

---

cell/view/WorkbookView.js
common/Drawings/CommonController.js
common/editorscommon.js
slide/Editor/Format/Presentation.js
slide/api.js
word/Editor/Document.js
word/Editor/DocumentContent.js
word/Editor/DocumentContentBase.js
word/Editor/DocumentContentElementBase.js
word/Editor/DocumentControllerBase.js
word/Editor/DrawingsController.js
word/Editor/Endnotes.js
word/Editor/Footnotes.js
word/Editor/HeaderFooter.js
word/Editor/HeaderFooterController.js
word/Editor/LogicDocumentController.js
word/Editor/StructuredDocumentTags/BlockLevel.js
word/Editor/Table.js
word/api.js

Refactor copy/paste formatting

Fix bug #61779

---

word/apiBuilder.js

Broken documentation on master

Fix documentation

---

common/apiBase_plugins.js

ignore asc_plugins_installed, asc_plugins_removed in desktop version

bug fix: incorrect cache

---

cell/apiBuilder.js
common/apiBase_plugins.js
word/apiBuilder.js
word/api_plugins.js

Api docs fixes for 7.4

---

cell/model/Workbook.js
tests/cell/spreadsheet-calculation/SheetStructureTests.js

Fixed bug - didn't work range with 8+ cells

[se] Fixed bugs autofill day of week + Unit tests

---

word/Editor/Endnotes.js
word/Editor/Footnotes.js
word/Editor/Paragraph.js

Rework paragraph selection with the mouse the way MSWord does

Fix bug #62899

---

word/Editor/Document.js
word/Editor/Paragraph.js

Implement option for smart paragraph selection

Fix bug #63270

---

word/Editor/Paragraph.js

Do not select empty paragraph with smart selection

Fix bug #63304

---

word/Editor/Paragraph.js

Fix smart selection with empty math equations

Fix bug #63323

---

common/plugins/plugin_base_api.js
word/apiBuilder.js

Api docs updates

---

cell/apiBuilder.js

Fix object descriptions

---

common/plugins/plugin_base_api.js

86ac715d315abfcfea840ee19593ce16092697d9

return description for executeCommand and hide for documentation

---

cell/api.js
cell/model/clipboard.js
cell/view/WorkbookView.js
cell/view/WorksheetView.js
common/wordcopypaste.js
slide/api.js

[se][pe] Add callback after paste date for plugins.

For bug #62542.

---

build/Gruntfile.js

Fix bug 64327

---

cell/model/FormulaObjects/traceDependents.js

Added a check for a shared listener range as well as an index shift based on the result of the getSharedIntersect function

[se] Fix bug 64317

---

common/editorscommon.js

Fix checking for identical characters

For bug 59580

---

common/plugins.js

Change which plugin we return after removing.

Fix bug #64475.

---

word/apiBuilder.js

Fixes for api docs 7.5

---

pdf/src/annotations/text.js
pdf/src/graphics.js

Fix drawing annotation icon in IE

Fix bug #64691

---

common/apiBase_plugins.js

Change how we detect desktop for some plugins method.

Fix bug #64720

---

word/Math/NamesOfLiterals.js
word/Math/UnicodeParser.js
word/Math/mathContent.js

- Add processing of prescripts

Fix bug #30096

---

cell/model/FormulaObjects/dateandtimeFunctions.js
common/NumFormat.js
tests/cell/spreadsheet-calculation/FormulaTests.js

Refactoring the DAYS formula. Added tests. And added a condition for a positive fractional number less than one when converting to a date.

[se]Fix bug 49355

---

cell/model/FormulaObjects/parserFormula.js
cell/model/FormulaObjects/statisticalFunctions.js
tests/cell/spreadsheet-calculation/FormulaTests.js

Updated the action when performing arithmetic operations with matrices of different sizes

[se] For bug 46246

---

common/Charts/ChartsDrawer.js

[se][charts] Fix crash charts draw

---

cell/model/FormulaObjects/lookupandreferenceFunctions.js
cell/model/FormulaObjects/parserFormula.js
cell/model/Workbook.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Added binarySearch and getLastMatch functions for LOOKUP formula
- Added LOOKUPCache and its use in calculations
- Function general refactroring

[se]Fix bug 38998

---

cell/model/FormulaObjects/mathematicFunctions.js
cell/model/FormulaObjects/statisticalFunctions.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Сhanged the behavior of the POWER function when working with matrices of different sizes
- Changed the selection of matrix elements in the lcl_CalculateRowsDelta and lcl_CalculateRowMeans functions to universal. Added tests for the LINEST function

[se]Fix bug 65316

---

cell/model/Workbook.js

- Fix initialization oFilledCells object

[se] Fix bug #65448, fix bug #65421

---

cell/model/FormulaObjects/dateandtimeFunctions.js
cell/model/FormulaObjects/financialFunctions.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Fixed problem for calc_method in ACCRINT
- Added condition for exiting the formula when the coupon period is 0
- Added a fix in calculations for the COUPPCD formula
- Added tests for ACCRINT and COUPPCD

[se] Fix bug 24266

---

cell/model/FormulaObjects/financialFunctions.js
tests/cell/spreadsheet-calculation/FormulaTests.js

Changed the way to get dates for arguments, added tests and additional error handling

[se] Added fix for COUPNCD function

---

cell/model/Workbook.js
tests/cell/spreadsheet-calculation/SerialTests.js

- Refactor _fillExcelDate. Improved logic
- Fix logic for Date unit - Weekday

[se] Fix bug #65672, fix bug #65731

---

word/Editor/Document.js
word/Editor/Field.js

Fix changing text properties for a mail merge field

[de] Fix bug 65487

---

common/apiBase_plugins.js
common/plugins/plugin_base_api.js

added the pdf editor type to api docs

Api docs for plugins

---

word/Editor/Document.js

Fix calculation of the document with flow paragraphs

Fix bug #65141

---

word/Editor/Paragraph/RunContent/Base.js
word/Editor/Paragraph/RunContent/Space.js
word/Editor/Paragraph/RunContent/Text.js

Fix an issue with calculating text when text spacing is negative and greater than the width of the letters

Fix bug #65476

---

word/Math/mathText.js

Add an exception for drawing the 200E character in a math equation

Fix bug #46069

---

word/Editor/Paragraph.js

Fix an issue with comments highlight

Fix bug #65947

---

word/Editor/Serialize2.js

Fix writing radio buttons to docxf

Fix bug #65305

---

word/Editor/Document.js

Fix an issue with sending event from sdk

Fix bug #65963

---

common/commonDefines.js

adding-arabic-format-and-fixed-chinese

---

cell/model/Workbook.js

- Added max limit for step value when using Weekday series

[se] Fiх bug #65731

---

cell/apiBuilder.js
slide/apiBuilder.js
word/apiBuilder.js

Fixes for api docs

---

word/Editor/Math.js
word/Editor/Paragraph/position-calculator.js
word/Math/base.js
word/Math/mathContent.js

Fix an issue with calculating the cursor position beyond a math equation

Fix bug #66195

---

word/Editor/Paragraph/draw/highlight-draw-state.js

Fix rendering of text highlight

Fix bug #66140

---

word/Editor/Paragraph/draw/content-draw-state.js
word/Editor/Paragraph/draw/line-draw-state.js

Fix rendering of underline text with an anchored image in it

Fix bug #66129

---

word/Drawing/Graphics.js

Fix rendering coplext script text in the tooltip of header/footer

Fix bug #66162

---

word/Editor/Paragraph/TextShaper.js

Fix an issue with rendering ligatures for RTL text

Fix bug #66146

---

word/Drawing/Graphics.js

Decrease the header/footer label to normal size

Fix bug #66230

---

word/Editor/Paragraph/search-position-by-coords.js

Fix bug #66220

---

word/Editor/Paragraph/draw/highlight-draw-state.js

Fix an issue with handling click on comment

Fix bug #66227

---

word/Editor/Paragraph/search-position-by-coords.js

Fix canceling the selection when opening context menu for rtl text

Fix bug #66222

---

word/Editor/Math.js
word/Editor/Paragraph.js
word/Editor/Paragraph/draw/highlight-draw-state.js
word/Math/base.js
word/Math/mathContent.js

Fix crash when clicking comment inside a math equation

Fix bug #66252

---

word/Editor/DocumentContentBase.js

Don't send any events when collecting info for the text speaker

Fix bug #66217

---

word/Editor/Paragraph/draw/highlight-draw-state.js

Fix problem with comments over rtl text

Fix bug #66255

---

common/Drawings/DrawingsChanges.js
slide/Editor/CollaborativeEditing.js
slide/Editor/Format/Presentation.js
slide/Editor/Format/Slide.js
slide/api.js

Remove unusual locks for selected slides

---

word/Editor/Paragraph/draw/highlight-draw-state.js

Fix a problem with rendering collaboration highlight

Fix bug #66276

---

word/Drawing/buttons.js

Fix text label for TOC in the RTL UI

Fix bug #66278

---

word/Editor/Paragraph.js
word/Editor/Paragraph/draw-selection.js

Fix an issue with selection bounds in the mobile web

Fix bug #66351

---

common/libfont/textshaper.js

Fix an issue with shaping text with different direction

Fix bug #66317

---

word/Editor/Common.js
word/Editor/Document.js

Fix an issue with correction of a text selection when passing through a complex field

Fix bug #66384

---

word/Editor/Paragraph.js
word/Editor/Paragraph/position-calculator.js

Fix an issue with calculating the current cursor position in some cases

Fix bug #66376

---

slide/apiBuilder.js

fixed ApiPresentation/GetAllComments docs

Fix for api docs

---

common/apiCommon.js

This is necessary for the cell api builder method "AddCustomFunction".

[all] Add function for parsing js doc.

---

word/Editor/SelectedContent.js
word/api.js

Fix an issue with the last paragraph dissappearing when inserting content using the plugin

Fix bug #66727

---

word/api.js

Fix issue with specifying text shade color

Fix bug #66826

---

common/apiBase_plugins.js

Fix problem with editing permission checking for some plugins methods.

[plugins] For bug #66927.

---

word/apiBuilder.js

updated api docs for the ApiTextPr methods

Api docs for the ApiTextPr methods

---

cell/model/FormulaObjects/parserFormula.js
tests/cell/spreadsheet-calculation/FormulaTests.js

The SUM function has been added to the arrayFunctionsMap list

[se] Fix bug 66800

---

common/CollaborativeEditingBase.js
common/Drawings/Format/GraphicObjectBase.js
common/commonDefines.js
common/editorscommon.js
slide/Editor/CollaborativeEditing.js
slide/Editor/Format/Comments.js
slide/Editor/Format/Presentation.js
slide/Editor/Format/Slide.js
slide/api.js
word/Drawing/Graphics.js
word/Editor/CollaborativeEditing.js
word/Editor/Comments.js
word/Editor/Numbering/AbstractNum.js
word/Editor/Numbering/Num.js
word/Editor/Paragraph.js
word/Editor/RevisionsChange.js
word/Editor/StructuredDocumentTags/BlockLevel.js
word/Editor/Table.js
word/Editor/Table/TableDraw.js
word/api.js

AscCommon.locktype_None/locktype_Mine/locktype_Other/locktype_Other2/locktype_Other2 -> AscCommon.c_oAscLockTypes

[all] Replace constants

---

cell/model/FormulaObjects/parserFormula.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Added LOOKUP function to arrayFunctionMap

[se] Fix bug 62730

---

cell/api_plugins.js
cell/model/CellComment.js
slide/Editor/Format/Comments.js
slide/api_plugins.js

[se][pe] Add plugin method "GetAllComments".
Also add method "ConvertToSimpleObject" to "asc_CCommentData" and "CCommentData".

Fix bug #67122

---

cell/apiBuilder.js

Add note for "Set..." methods to "ApiFont" class.

[se] Update builder documentation.

---

cell/model/FormulaObjects/lookupandreferenceFunctions.js
tests/cell/spreadsheet-calculation/FormulaTests.js

Added check for real array size in FILTER function

[se]Fix bug 64954

---

cell/api.js
cell/graphics/DrawingContext.js

Fix crash when opening version history in spreadsheet editor

Fix bug #67263

---

word/Editor/StructuredDocumentTags/Custom/DatePicker.js

Return format examples from Asc.c_oAscDateTimeFormat list for DatePicker form

Fix bug #63495

---

word/Editor/Paragraph.js

Fix cursor position correction

Fix bug #67339

---

word/Editor/Paragraph/TextShaper.js
word/Editor/Run.js

Fix rendering instrText in case it doesn't lie in a complex field

Fix bug #66937

---

word/api.js

Fix crash after changing a content control placeholder using plugin method

Fix bug #67251

---

common/Drawings/GraphicsBase.js
common/Drawings/TextDrawer.js
word/Math/base.js
word/Math/nary.js

Fix issue with math nary object rendering

Fix bug #67188

---

cell/view/StringRender.js

Fix char width calculation for subscript/superscript text

Fix bug #67412

---

cell/view/CellTextRender.js
cell/view/StringRender.js

Fix vertical text rendering in the spreadsheet editor

Fix bug #67373

---

cell/view/CellEditorView.js
cell/view/CellTextRender.js

Remove code points from a combined character one at a time when removing occurs from the end of the character

Fix bug #67333

---

word/Editor/Paragraph/search-position-by-coords.js
word/Editor/Run.js

Fix an issue with detecting the cursor position

Fix bug #66987

---

cell/model/FormulaObjects/dateandtimeFunctions.js
cell/model/FormulaObjects/parserFormula.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Added areaIndexesType in parserFormula to use

[se]Fix bug 40648

---

cell/model/FormulaObjects/lookupandreferenceFunctions.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Added a fix for processing arrays and ranges for the first and third arguments in the V/H HLOOKUP functions

[se] Fix/VHLookup-function-fix

---

common/Drawings/Format/Format.js
slide/Drawing/DrawingDocument.js
slide/Drawing/anim-pane.js

Add deep comparing of actual Timing tree and animation pane's sequence structure (instead of comparing by CSeq only)

Fix bug #67632

---

slide/Drawing/anim-pane.js

Loop happens:
1. With open anim pane delete shape with anim effect
2. Undo changes

Add tmp fix for playButton label width bug

---

cell/model/FormulaObjects/lookupandreferenceFunctions.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Fixed calculation when receiving an array as the first argument in CHOOSE function

[se]Fix bug 67639

---

word/Editor/StructuredDocumentTags/Custom/CheckBox.js
word/Editor/StructuredDocumentTags/SdtPr.js

Fix an issue with changing checkbox key

Fix bug #67458

---

cell/view/StringRender.js

Fix rendering cells with repeated char

Fix bug #67749

---

word/api.js

Add the method for changing a page numbering format to export

Fix bug #67947

---

slide/Drawing/DrawingDocument.js

Add title & subtitle update when changing corresponding object properties

Fix bug #67603

---

cell/model/FormulaObjects/financialFunctions.js
cell/model/FormulaObjects/parserFormula.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Fixed caclulations in ACCRINT formula
- Added a constant for the maximum date used in the editor

[se]Fix bug 24266

---

word/Math/mathContent.js

Fix an issue with finding the word start/end pos in a math equation

Fix bug #68009

---

slide/Drawing/anim-pane.js

Add default case for choosing effect bar colors

Fix bug #68150

---

cell/model/FormulaObjects/parserFormula.js
cell/model/Workbook.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Convergent formula don't change value when recalculates cells.
- Optimization of logic

[se] Fix convergent formula

---

cell/model/WorkbookElems.js

Added asc_getArgName function by CCustomFunctionInfo

[se] By bug 68026

---

common/Charts/ChartsDrawer.js
common/Drawings/Format/ChartEx.js
common/Drawings/Format/ChartFormat.js
common/Drawings/Format/ChartSpace.js
common/SerializeChart.js
tests/cell/spreadsheet-calculation/FormulaTests.js

[all] Funnel chart added to charts

---

word/Editor/Paragraph/RunContent/PageNum.js
word/Editor/Paragraph/RunContent/PagesCount.js

Fix adding an number of pages element to a document

Fix bug #68048

---

word/Editor/Paragraph_Recalculate.js
word/Editor/Run.js

Fix an issue with clipping inline shape

Fix bug #59051

---

word/Editor/Paragraph/ComplexField.js
word/Editor/Run.js

Fix NUMPAGES field in a FORMULA field

Fix bug #68371

---

cell/api.js

[se] By bug 68396

---

common/Charts/ChartsDrawer.js

Effect of errBars on catAxis fixed

[all] ErrBars impact on diagram bug fixed

---

word/Editor/Paragraph.js

Fix an issue with restoring selection state of the paragraph

Fix bug #68405

---

word/Editor/Serialize2.js
word/Editor/document/document-background.js

Do not write white page color to the file

Fix bug #68354

---

common/CollaborativeEditingBase.js
common/workerspeech.js

Fix an issue with undo in collaboration when screen reader support is enabled

Fix bug #68468

---

cell/model/FormulaObjects/mathematicFunctions.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Added type checking for function arguments

[se] Fix bug 58684

---

cell/model/FormulaObjects/traceDependents.js
tests/cell/spreadsheet-calculation/FormulaTrace.js

- Added fix when the dependency was not drawn for named ranges inside the formula

[se] Added fix for dependents traces 

---

cell/model/FormulaObjects/lookupandreferenceFunctions.js
cell/model/FormulaObjects/parserFormula.js
cell/model/FormulaObjects/statisticalFunctions.js
tests/cell/spreadsheet-calculation/FormulaTests.js

- Fixed incorrect calculation result when an array was returned with rownum or colnum equal zero
- Added tests

[se] Added fix for INDEX calculation

---

tests/word/numbering/numberingAutocorrect.js
tests/word/numbering/numberingCalculation.js
word/Editor/Document.js
word/Editor/DocumentContentBase.js
word/Editor/DocumentContentElementBase.js
word/Editor/History.js
word/Editor/Numbering/AbstractNum.js
word/Editor/Numbering/NumberingApplicator.js
word/Editor/Paragraph.js
word/Editor/Paragraph/Run/RunAutoCorrect.js
word/Editor/ParagraphChanges.js
word/Editor/Serialize2.js
word/Editor/Styles.js
word/Editor/Styles/FixedFormDefaults.js
word/apiBuilder.js
word/fromToJSON.js

Fix an issue with reading numbering properties in styles. Also refactor using AscWord.NumPr class

Fix bug #66749

---

cell/model/FormulaObjects/parserFormula.js
cell/model/WorkbookElems.js
cell/view/CellEditorView.js
cell/view/WorkbookView.js
common/editorscommon.js
tests/cell/spreadsheet-calculation/SheetStructureTests.js

- Added parsing of the "@" symbol for tables to processing

[se] Fix bug 56880

---

pdf/src/annotations/base.js
pdf/src/annotations/freeText.js

For bug 65822

---

cell/model/FormulaObjects/parserFormula.js

- Fixed crash editor while opening file.

[se] Fix bug 69511

---

word/Editor/GraphicObjects/Format/ShapePrototype.js
word/Editor/Paragraph/ComplexField.js
word/Editor/Run.js

Handle PAGE/NUMPAGES complex fields when there are no separate char in this field

Fix bug #69710

---

cell/model/FormulaObjects/parserFormula.js
tests/cell/spreadsheet-calculation/SheetStructureTests.js

- Changed string processing when receiving arguments in the wizard
- Added tests

[se] Fix bug 61856

---

word/Math/NamesOfLiterals.js

- fix Wrap of MathText in WrapExactElement

[de] Fix bug #69475

---

word/Math/nary.js

- previously made merge (far in past) created this problem

[de] Fix bug #69681
